### PR TITLE
add Escher maps with automatic reaction box mapping

### PR DESCRIPTION
**Pull request by axelvonkamp**

### CODE REVIEW

**Comment by VonAlphaBisZulu** [comment]
Tested with iMM904. No warning, no errors, no bugs. Works perfectly for near to all reactions! The only exceptions I see so far are reactions with "_copy1" at the end. In other reactions, underscore is recognized correctly.

image
image

**Review by VonAlphaBisZulu — APPROVED** [review]

**Comment by axelvonkamp** [comment]
Yes, so far boxes are only put at positions where IDs match exactly, which works as long as both the model and the Escher map use the same IDs.

**Comment by VonAlphaBisZulu** [comment]
> Yes, so far boxes are only put at positions where IDs match exactly, which works as long as both the model and the Escher map use the same IDs.

This seems to be the case for [iMM904 (zip)](https://github.com/cnapy-org/CNApy/files/7828780/iMM904.zip):
in the svg-file l. 2196
`<text class="reaction-label label" visibility="visible">ALCD2x_copy1</text>`
in the sbml-file l. 54125
` <reaction id="R_ALCD2x_copy1" fast="false" reversible="false" name="Alcohol dehydrogenase (ethanol)" metaid="R_ALCD2x_copy1" sboTerm="SBO:0000176" fbc:upperFluxBound="cobra_default_ub" fbc:lowerFluxBound="cobra_0_bound">`

**Comment by axelvonkamp** [comment]
I guess this is a just glitch of this particular map. In such a case the correct reaction box needs to be added manually by the user.

**Comment by VonAlphaBisZulu** [comment]
Agreed, no big deal. Thanks for the new feature!

**Pull request merged**
