### PR TITLE
Add default concentration ranges in thermodynamic dialog

### PR DESCRIPTION
**Pull request by Paulocracy**
Such ranges can be still also set through JSON or Excel XLSX files.

### CODE REVIEW

**Comment by Paulocracy** [comment]
Ah it is already implemented such that, if only either a Cmin or Cmax is given, the default other value is used while the given one is respected. I thought that the "and/or" can be understood in this way, but obviously not :3 Do you have an idea how to rephrase it better?

**Comment by axelvonkamp** [comment]
Hmm. "Default 'Cmin' and 'Cmax' values (in [M]) that will be used unless defined in the metabolite annotation:"

**Comment by Paulocracy** [comment]
Great idea :D I rephrased it a bit for a new review :-)

**Review by axelvonkamp — APPROVED** [review]
This is very helpful.

**Pull request merged**
