### PR TITLE
Refactored annotation widget

### PR DESCRIPTION
**Pull request by Paulocracy**
In the great refactoring quest, I created a common annotation widget for the reaction and metabolite lists. It does not provide new functions up to now, although they are now much easier to implement.

### CODE REVIEW

**Comment by Paulocracy** [comment]
Now, it also contains a "-" button :D

**Comment by axelvonkamp** [comment]
You could also add this to the genes list, they can have annotations too.
When deleting an annotation this is not yet recognized as a model change.
I sporadically get errors like
Traceback (most recent call last):
  File "/scratch/vonkamp/gwdg_owncloud/CNApy/cnapy/gui_elements/reactions_list.py", line 725, in emit_delete_annotation
    del(self.reaction.annotation[keys[row]])
IndexError: list index out of range
when deleting rows. Most of the times it works though.

**Comment by axelvonkamp** [comment]
This 
del(self.reaction.annotation[keys[row]])
is also potentially dangerous because the row index in the table could change if e.g. sorting were allowed. It would be safer (and more efficient) to emit the annotation key of the row that is to be deleted directly and not the row index.

**Comment by Paulocracy** [comment]
Great points! I just added commits which use the key for annotation deletions, and I also added annotations for genes.

**Comment by axelvonkamp** [comment]
Does "(first)" for open in browser refer to the possibility that there are multiple annotations for one key? Maybe in that case mutltiple tabs should be opened, as many as there are annotations for this key. I am not sure though, if this would be really better...

**Comment by Paulocracy** [comment]
Yes this refers to the case that there are multiple annotations. I restricted it to the first one because, in an ideal database, they should be referenced to each other anyway through the connection of the used element, and because there are elements with dozens of annotations which could break a weaker device when dozens of tabs are opened :3

**Comment by axelvonkamp** [comment]
When deleting an annotation it appears that "unsaved changes" is still not set?

**Comment by Paulocracy** [comment]
I just fixed another error if only one annotation remained as this annotation couldn't be deleted, and I added the unsaved changes signalling.

**Review by axelvonkamp — COMMENTED** [review]
The function name "emit_delete_annotation" does not seem appropriate as it does not emit any signal. It could also be decorated as "@Slot()".

**Comment by Paulocracy** [comment]
Good point, I renamed the function, however, I don't see how Slot() would help, can you explain your reasoning?

**Review by axelvonkamp — CHANGES_REQUESTED** [review]
The "keys" variable in delete_selected_annotation is now unused and can be removed.

**Comment by Paulocracy** [comment]
Another good point, it's done

**Comment by axelvonkamp** [comment]
> Good point, I renamed the function, however, I don't see how Slot() would help, can you explain your reasoning?

Just to make it clear that it is supposed to act as a Slot for Signals. Also, someone on Stackoverflow claimed that setting up connections to decorated slots is faster, have no idea if this is true xD

**Comment by Paulocracy** [comment]
> Just to make it clear that it is supposed to act as a Slot for Signals. Also, someone on Stackoverflow claimed that setting up connections to decorated slots is faster, have no idea if this is true xD

Ok I just tried but it just seems to be unnecessary overhead for the function as it would also require one more parameter, and up to know it looks fast enough for me :3

**Review by axelvonkamp — DISMISSED** [review]
Looks fine

**Comment by Paulocracy** [comment]
@axelvonkamp I just need a new review as I just resolved the conflict with main :3

**Review by axelvonkamp — APPROVED** [review]

**Pull request merged**
