### PR TITLE
Add new installation instructions

### PR DESCRIPTION
**Pull request by Paulocracy**
In the light of our latest problem with the CNApy installer, I propose a new installation protocol (which successfully resolved the latest installation issue) where the installation of Miniconda and cnapy is only semi-automated. Also, this method works for all common operating systems. Feel free to share your thoughts about this installation protocol proposal :-)

The associated installation assistant script can be found [here](https://github.com/cnapy-org/CNApy/files/10859991/assistant_scripts.zip). The would be added to all future releases as assets.

### CODE REVIEW

**Comment by axelvonkamp** [comment]
Is having to copy the scripts into the condabin folder and executing them really simpler than just copying & pasting the contained command into the conda shell?

**Comment by Paulocracy** [comment]
One advantage is that users who would shy away from the console would jsut have to double-click on a file.

**Review by axelvonkamp — DISMISSED** [review]
Excellent

**Comment by Paulocracy** [comment]
More excellence is incoming :D

**Pull request merged**
