### PR TITLE
new option to cache results from FVA and MCS preprocessing

### PR DESCRIPTION
**Pull request by axelvonkamp**

### CODE REVIEW

**Comment by Paulocracy** [comment]
I'm not sure if I missed anything but even with an updated Anaconda environment (optang_enumerator==0.0.7), I get the following error and I'm unable to start CNApy:
```
  File "G:\GitHub\CNApy_Org\CNApy\cnapy\appdata.py", line 12, in <module>
    from optlang_enumerator.cobra_cnapy import CNApyModel
ModuleNotFoundError: No module named 'optlang_enumerator.cobra_cnapy'
```

**Comment by axelvonkamp** [comment]
Did you use conda install to get the latest optlang_enumerator? The CI tests appear to have worked.

**Comment by Paulocracy** [comment]
Yes I also did it with conda install, I also tried it by reinstalling the environment, but you're probably right that the problem lies on my side as the tests work :3

**Comment by axelvonkamp** [comment]
> Yes I also did it with conda install, I also tried it by reinstalling the environment, but you're probably right that the problem lies on my side as the tests work :3

Does 'conda list' then show that version 0.0.7 is installed?

**Review by Paulocracy — APPROVED** [review]
After solving my Anaconda issue (which was caused by a strange package cache error) I was finally able to succesfully try the cache usage implementation with different models, model scenarios and with MCS preprocessing as well as FVA.

**Pull request merged**
