### PR TITLE
Refactored reaction tree

### PR DESCRIPTION
**Pull request by Paulocracy**
I just refactored the reaction tree of the metabolite mask into a separate class which is now also used by the genes list.
*Almost* everything works, except of swtching to a double-clicked metabolite in the genes list. I fiddled with the associated signals but could not make it work, so that help in solving this issue would be very appreciated :-)

### CODE REVIEW

**Comment by axelvonkamp** [comment]
Shouldn't it be ReactionTableWidget instead of ReactionTreeWidget?

**Comment by Paulocracy** [comment]
Yes that should be a better name, I'll change it

**Comment by Paulocracy** [comment]
I just renamed it, and I finally managed to solve the problem, I was always overlooking the GeneList class which was never emitting the jumpToMetabolite signal :3

**Review by axelvonkamp — APPROVED** [review]
Excellent

**Pull request merged**
