### PR TITLE
Revision

### PR DESCRIPTION
**Pull request by axelvonkamp**

### CODE REVIEW

**Comment by axelvonkamp** [comment]
The persistent coloring schemes commit is not a very elegant solution because the default coloring scheme is still used during the update() calls. The heatmap or on/off style is then just applied afterwards automatically.

**Comment by Paulocracy** [comment]
I found two things @axelvonkamp : A) A small typo that I just fixed ^^ and B) I'm not sure if the LB/UB view should switch again to the default UB/LB (i.e., by disregarding the last FVA) whenever the user types in a new scenario (i.e., any number in any of the reaction boxes) since this would quite possibly change the FVA results. What do you think?

**Review by Paulocracy — APPROVED** [review]
All fine as far as I checked it :-)

**Review by Paulocracy — APPROVED** [review]
Now, even the conflict with master is solved

**Pull request merged**
