### PR TITLE
Fix concentration setting

### PR DESCRIPTION
**Pull request by Paulocracy**
While testing 1.1.5, I found a fatal bug with the concentrations loading, so that I hereby propose a fix and version 1.1.6 :-)

### CODE REVIEW

**Review by axelvonkamp — APPROVED** [review]
Looks good

**Comment by axelvonkamp** [comment]
The dialogs are stored as attributes of the MainWindow oject (e.g. self.optmdfpathway_dialog). Since they are locally used within one function these could just be normal variables (e.g. optmdfpathway_dialog).

**Comment by Paulocracy** [comment]
@axelvonkamp Done

**Review by axelvonkamp — APPROVED** [review]
Go!

**Pull request merged**
