### PR TITLE
Search for annotation values

### LINKED ISSUE #268: Allow search in all metabolite/reaction attributes
Currently only IDs and names are searched via the search bar, but sometimes it would be convenient to search the gene rules and annotations as well. Since the search bar is very long one could place a set of check boxes on the right where one then can select which attributes to search.

### PR DESCRIPTION
**Pull request by Paulocracy**
Theses commits aim to fix #268. I refactored the search routine into one single function in utils.py, but maybe there's a better place (and type annotation) for it. Although many new for loops are introduced if one searches for annotation values, I don't have problems with the search speed up to now.
**At least one issue still remains**: In Escher, I didn't find a way to search for multiple completely different IDs as it might be the case with the annotation search. Up to now, only reactions which have a match with the search bar entry are highlighted but not all found reactions with a given annotation match.

### CODE REVIEW

**Comment by Paulocracy** [comment]
Addendum: I think that the GPR search is not interesting anymore due to the Genes tab and its reaction display.

**Comment by axelvonkamp** [comment]
> Addendum: I think that the GPR search is not interesting anymore due to the Genes tab and its reaction display.

Yes, I agree we can drop this.

**Comment by Paulocracy** [comment]
Good idea with the Escher maps! I added a commit where +Annotation is disabled (and not read out) whenever an Escher map is opened. I also thought about a search index, however, it would have to be synchronized with the cobrapy model which would mitigate its intention of lowering computational times :3

**Review by axelvonkamp — APPROVED** [review]
Its nice to be able to include annotations in search now, thanks.

**Pull request merged**
