### PR TITLE
Collection of bug fixes

### PR DESCRIPTION
**Pull request by Paulocracy**
See commit comments for the possibly resolved issues

### CODE REVIEW

**Comment by axelvonkamp** [comment]
How can it happen that in mcs_dialog.py self.eng is None when appdata.selected_engine is not None? This should not occur, it would be good to find the reason for this and fix it.

**Comment by axelvonkamp** [comment]
> 
> 
> How can it happen that in mcs_dialog.py self.eng is None when appdata.selected_engine is not None? This should not occur, it would be good to find the reason for this and fix it.

I think I have found the problem. In mcs_dialog.py the condition is
if appdata.selected_engine == 'None':
but it probably should be
if appdata.selected_engine == None:

**Comment by Paulocracy** [comment]
Great find :D And yes, "None" is just a string, and None is Python's undefined/NaN symbol

**Comment by axelvonkamp** [comment]
> 
> 
> Great find :D And yes, "None" is just a string, and None is Python's undefined/NaN symbol

Or perhaps not as simple as that, it appears that selected_enginge can sometimes be 'None' and sometimes None, need to investigate this further...

**Comment by axelvonkamp** [comment]
> 
> 
> > Great find :D And yes, "None" is just a string, and None is Python's undefined/NaN symbol
> 
> Or perhaps not as simple as that, it appears that selected_enginge can sometimes be 'None' and sometimes None, need to investigate this further...

So it turns out to be 'None' when read from the cnapy-config.txt file but it is None when set via the Configure CNApy dialog. Perhaps we should use the string 'None' consistently to denote that there is no engine because the alternative values ('octave', 'matlab') are strings too. What do you think?

**Comment by Paulocracy** [comment]
+1 we should stick to the same data type since it will make the typing later on easier :-)

**Comment by Paulocracy** [comment]
@axelvonkamp As discussed, I've changed None to "None" and deleted the (now unneccessary) None check again, you can check it in the 2 newest commits

**Comment by sthiele** [comment]
Also look at ApData
https://github.com/cnapy-org/CNApy/blob/3dcf6391d4688fa3b996aa39156856c4a640b7fe/cnapy/appdata.py#L24-L26

**Comment by Paulocracy** [comment]
Good point @sthiele :-), I thought that the selected engine and the engine are separated but this doesn't seem to be the actual case, so that I changed it for the config dialog as well as in the app data in the newest commit. Since I don't have all engines on my system, testing on other systems is desirable :D

**Comment by axelvonkamp** [comment]
I am not sure that it was necessary to also touch self.engine where None was fine so far?

**Comment by Paulocracy** [comment]
I think it's easier to maintain one single data type instead of a str | None union, but yes, it needed even more changes than I thought ^^

**Comment by axelvonkamp** [comment]
> 
> 
> I think it's easier to maintain one single data type instead of a str | None union, but yes, it needed even more changes than I thought ^^

Yes, but self.engine/matlab_engine/octave_engine contain ojects and not strings.

**Comment by axelvonkamp** [comment]
I have just pushed a new branch (selected_engine) to show what I would change.
There is also a failed check now, but I am not sure what happened there....

**Comment by Paulocracy** [comment]
@axelvonkamp So do you suggest that only selected_engine is changed?
And I also don't know what happened in the failed test, at first sight it doesn't look like a CNApy-related problem :O

**Comment by axelvonkamp** [comment]
> @axelvonkamp So do you suggest that only selected_engine is changed?

Yes, because this is probably the cause why the reviewers could not launch MCS computation. Changing self.engine/matlab_engine/octave_engine risks new bugs...

**Comment by Paulocracy** [comment]
Alright @axelvonkamp then I'll post an other pull request without the commits, can you create a pull request four your changes?

**Pull request closed without merging**
