### PR TITLE
separate dialog for configuration of CNA bridge

### PR DESCRIPTION
**Pull request by axelvonkamp**

### CODE REVIEW

**Comment by Paulocracy** [comment]
What is the intended behavior at the first start-up with this window separation?
And what is the general intention behind this?

**Comment by axelvonkamp** [comment]
The idea is to have the CNA bridge configuration separate because the Matlab/Octave tests are very time consuming which I find annoying to wait for when I just want to change e.g. the reaction box size.
Behaviour at start up is now only to download the models, there really is no need to force a configuration dialog because CNApy can just as well run without configuration file and use the default settings.

**Comment by Paulocracy** [comment]
I agree to your points, I would just suggest to add a notification pop-up window (or anything similar) on the first startup which tells the user that the configuration can be modified under the "Config" menu entry.

**Comment by axelvonkamp** [comment]
> 
> 
> I agree to your points, I would just suggest to add a notification pop-up window (or anything similar) on the first startup which tells the user that the configuration can be modified under the "Config" menu entry.

I don't think this is necessary because the "Config" menu is a top level menu that is directly visible.

**Comment by SteffKlamt** [comment]
I would also suggest to have at least a message window coming up when startin CNApy the first time to remind the user to check/adjust theses configurations.

**Pull request merged**
