### PR TITLE
Version 122

### PR DESCRIPTION
**Pull request by Paulocracy**

### CODE REVIEW

**Comment by axelvonkamp** [comment]
Is it necessary to always install openjdk in the installer scripts? The setup.py of efmtool_link should install a JDK if needed. At least for the CI tests it  appears to work.

**Comment by Paulocracy** [comment]
At least on systems without Java it is necessary, the efmtool_link requirements don't seem to suffice. Some check whether or not a correct JDK version could also work to prevent unneccessary JDK installations, although I'm not sure if there's a robust cross-platform way to do it.

**Comment by axelvonkamp** [comment]
I just tried the Windows installer. It works but at the beginning I see warning messages that commercial Anaconda channels are being used. I am not sure whether they have actually been used, is it safe to ignore these warnings?

**Comment by Paulocracy** [comment]
Yes you can see the warning if your global Anaconda config (which micromamba seems to use if there is one) still includes the default channel, you can remove it with ```conda config --remove channels defaults```. In any case, with the ```-c conda-forge``` argument in the bat's mamba command, I think that the default channel is not used anywhere.

**Review by axelvonkamp — DISMISSED** [review]
Nice work!

**Comment by Paulocracy** [comment]
Some links weren't displayed correctly, and I added conda-forge and openjdk to the conda instructions to prevent licensing problems and Java errors for the conda users

**Review by axelvonkamp — APPROVED** [review]

**Pull request merged**
