### PR TITLE
St/gui

### PR DESCRIPTION
**Pull request by sthiele**
This PR, contains some changes I made while reviewing. 

I also found something which might be a bug.

With the small exampke given this setup for mcs computation
grafik
 I get this error
```
Traceback (most recent call last):
  File "C:\Users\Sven\Projects\CNApy\cnapy\gui_elements\mcs_dialog.py", line 602, in compute_optlang
    exclude_boundary_reactions_as_cuts=self.exclude_boundary.isChecked())
  File "C:\Users\Sven\miniconda3\envs\cnapy-dev\lib\site-packages\optlang_enumerator\mcs_computation.py", line 386, in compute_mcs
    e.model.configuration.tolerances.optimality = mip_opt_tol
  File "C:\Users\Sven\miniconda3\envs\cnapy-dev\lib\site-packages\optlang\util.py", line 311, in __setattr__
    raise AttributeError(key + " is not an available tolerance parameter with this solver")
AttributeError: optimality is not an available tolerance parameter with this solver
```

### CODE REVIEW

**Comment by sthiele** [comment]
BTW: If you have more recent changes I can rebase my branch.

**Comment by axelvonkamp** [comment]
> 
> 
> This PR, contains some changes I made while reviewing.
> 
> I also found something which might be a bug.
> 
> With the small exampke given this setup for mcs computation
> grafik
> I get this error
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\Sven\Projects\CNApy\cnapy\gui_elements\mcs_dialog.py", line 602, in compute_optlang
>     exclude_boundary_reactions_as_cuts=self.exclude_boundary.isChecked())
>   File "C:\Users\Sven\miniconda3\envs\cnapy-dev\lib\site-packages\optlang_enumerator\mcs_computation.py", line 386, in compute_mcs
>     e.model.configuration.tolerances.optimality = mip_opt_tol
>   File "C:\Users\Sven\miniconda3\envs\cnapy-dev\lib\site-packages\optlang\util.py", line 311, in __setattr__
>     raise AttributeError(key + " is not an available tolerance parameter with this solver")
> AttributeError: optimality is not an available tolerance parameter with this solver
> ```

Yes, but this has already been fixed in the latest version of optlang_enumerator

**Comment by axelvonkamp** [comment]
> 
> 
> BTW: If you have more recent changes I can rebase my branch.

Well, I have a lot of changes in my pull request, so I wonder if we will get a lot of conflicts when we want to merge both PR?

**Comment by axelvonkamp** [comment]
> 
> 
> BTW: If you have more recent changes I can rebase my branch.

Yes, I have more changes, but they are not commited yet. Although multi-select and dragging basically work, there are still potential glitches, but perhaps it is not necessary to fix them all before the next commit. So should we wait for my next commit before merging?

**Comment by sthiele** [comment]
You can just commit to your `gui` branch, and trigger me when you are ready. I can then take care of rebasing and resolving eventual conflicts. If you like I can also drop the formatting commit e26a923d7951e53345f4b8b5c100e8f33414f82a which introduces many changes.
There is no need merge this quick into master.

**Comment by sthiele** [comment]
I'm closing this PR. As my fixes are unrelated to your gui branch I rebased them on master in `st/fixes` #319 
For the formatting we should probably syncronize at one point to get this done.

**Pull request closed without merging**
